### ISSUE TITLE
cmake/android.cmake file is missing

### ISSUE THREAD

**Issue by EwoutH** [webmproject/sjpeg#111]
I'm currently trying to build for Android. According to the [Readme](https://github.com/webmproject/sjpeg#compiling-with-android-ndk) there should be a file `android.cmake` in the `cmake` directory, but that one seems to be missing.

**Comment by skal65535** [comment]
On Thu, Apr 22, 2021 at 6:24 PM Ewout ter Hoeven ***@***.***>
wrote:

> I'm currently trying to build for Android. According to the Readme
> <https://github.com/webmproject/sjpeg#compiling-with-android-ndk> there
> should be a file android.cmake in the cmake directory, but that one seems
> to be missing.
>

Yes, it was missing from pull request #107
<https://github.com/webmproject/sjpeg/pull/107>, i'm fixing this right now
(along with few other missing things)

thanks!
skal/

**Comment by skal65535** [comment]
Hi,

On Thu, Apr 22, 2021 at 6:30 PM Pascal Massimino ***@***.***>
wrote:

>
>
> On Thu, Apr 22, 2021 at 6:24 PM Ewout ter Hoeven ***@***.***>
> wrote:
>
>> I'm currently trying to build for Android. According to the Readme
>> <https://github.com/webmproject/sjpeg#compiling-with-android-ndk> there
>> should be a file android.cmake in the cmake directory, but that one
>> seems to be missing.
>>
>
> Yes, it was missing from pull request #107
> <https://github.com/webmproject/sjpeg/pull/107>, i'm fixing this right
> now (along with few other missing things)
>

should be ok now, with #112 <https://github.com/webmproject/sjpeg/pull/112>.
Sorry about that!

skal/

**Comment by EwoutH** [comment]
Thanks a lot for the quick fix! It now successfully builds on my CI configuration, for which I added a PR with #113.
